apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
  namespace: config-management-system
spec:
  clusterName: gscrp-cs-cluster-001
  sourceFormat: unstructured
  git: 
    secretType: ssh
    syncRepo: git@github.com:/g-awmalik/acm-cis-demo.git
    syncBranch: wp-cis
    policyDir: config/root
  policyController:
    enabled: true
    templateLibraryInstalled: true
