apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  name: config
  namespace: "gatekeeper-system"
spec:
  match:
  - excludedNamespaces: ["kube-system", "gatekeeper-system", "config-management-system", "resource-group-system"]
    processes: ["audit"]

