apiVersion: v1
kind: Service
metadata:
  namespace: wp
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
---
apiVersion: v1
kind: Pod
metadata:
  namespace: wp
  name: wp
  labels:
    app: wordpress
spec:
  containers:
    - image: wordpress
      name: wordpress
      ports:
      - containerPort: 80
        name: wordpress
