apiVersion: v1
kind: Service
metadata:
  namespace: wp
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
---
apiVersion: v1
kind: Pod
metadata:
  namespace: wp
  name: wp
  annotations:
    ## CIS FIX: addresses apparmor security profile
    container.apparmor.security.beta.kubernetes.io/wordpress: runtime/default
    ## CIS FIX: addresses seccomp profile
    container.seccomp.security.alpha.kubernetes.io/wordpress: runtime/default
  labels:
    app: wordpress
spec:
  containers:
    - image: wordpress
      name: wordpress
      ports:
        - containerPort: 80
          name: wordpress
      securityContext:
        # CIS FIX: was true, addresses securityContext
        privileged: false
        # CIS FIX: was true, addresses priviledge escalation
        allowPrivilegeEscalation: false
        # CIS FIX: addresses absense of runAsUser, should use a real userid
        runAsUser: 100
        # CIS FIX: allow only read-only root file system access
        readOnlyRootFilesystem: true
