apiVersion: v1
kind: Service
metadata:
  namespace: wp
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
---
apiVersion: v1
kind: Pod
annotations:
  ## CIS FIX: addresses apparmor security profile
  container.apparmor.security.beta.kubernetes.io/wordpress: runtime/default
  ## CIS FIX: addresses seccomp profile
  container.seccomp.security.alpha.kubernetes.io/wordpress: runtime/default
metadata:
  namespace: wp
  name: wp
  labels:
    app: wordpress
spec:
  containers:
    - image: wordpress
      name: wordpress
      ports:
        - containerPort: 80
          name: wordpress
